spring:
  application:
    name: e-shop

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  e-shop:
    app:
      jwt-cookie-name: springBootEshop

  app:
    jwt-secret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwt-expiration-ms: 300000000

  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework: info
    org.springframework.security: info
    org:
      hibernate:
        sql: info
    nl:
      ckarakoc:
        eshop: info

project:
  image: images/
