INSERT INTO categories (category_name) VALUES ('Books');
INSERT INTO categories (category_name) VALUES ('Electronics');
INSERT INTO categories (category_name) VALUES ('Clothing');
INSERT INTO categories (category_name) VALUES ('Home & Kitchen');
INSERT INTO categories (category_name) VALUES ('Sports & Outdoors');
INSERT INTO categories (category_name) VALUES ('Toys & Games');
INSERT INTO categories (category_name) VALUES ('Beauty & Personal Care');
INSERT INTO categories (category_name) VALUES ('Automotive');
INSERT INTO categories (category_name) VALUES ('Health & Wellness');
INSERT INTO categories (category_name) VALUES ('Office Supplies');
INSERT INTO categories (category_name) VALUES ('Garden & Outdoors');
INSERT INTO categories (category_name) VALUES ('Pet Supplies');
INSERT INTO categories (category_name) VALUES ('Books & Magazines');
INSERT INTO categories (category_name) VALUES ('Music & Instruments');
INSERT INTO categories (category_name) VALUES ('Movies & TV Shows');
INSERT INTO categories (category_name) VALUES ('Baby Products');
INSERT INTO categories (category_name) VALUES ('Jewelry & Accessories');
INSERT INTO categories (category_name) VALUES ('Tools & Hardware');
INSERT INTO categories (category_name) VALUES ('Software & Games');
INSERT INTO categories (category_name) VALUES ('Travel & Luggage');
